### ISSUE TITLE
Add proper reading list for site

### ISSUE THREAD

**Issue by mellybelly** [kltm/reusabledata-staging#59]
We should have a list of relevant reading materials. I will post these here, @kltm let me know what format we want and I can also make a file for them elsewhere.

**Comment by kltm** [comment]
For the export utilities that can be used (from experience doing this before), I've taken the bibtex drop and created a zotero group; I'll add my edits and notes there and re-export: https://www.zotero.org/groups/1713370/reusable_data

**Comment by kltm** [comment]
The re-exporting is going poorly; giving up for now and linking out to the in-progress bib/reading list with a comment.
