### ISSUE TITLE
Add acknowledgement footer

### ISSUE THREAD

**Issue by mellybelly** [kltm/reusabledata-staging#60]
Getting some ideas down here:

ReusableData.org was developed as part of the [Monarch Initiative](www.monarchinitiative.org) and the [NCATS Biomedical Data Translator](https://ncats.nih.gov/translator), where the reuse and free redistribution of publicly available data for disease discovery was burdensome. ReusableData.org was created to help others navigate the legal redistribution of public data and to help data providers make it easier for others to reuse their data.

ReusableData.org is funded by the National Center for Advancing Translational Sciences NCATS 
OT3 TR002019 as part of the Biomedical Data Translator project. 

We are grateful to the many original sources of our data for allowing their integration. 

Add something about licensing/attribution for images.

**Comment by mellybelly** [comment]
P.S. we need to make sure that all contributors are listed somewhere, but probably not in the footer

**Comment by kltm** [comment]
contributors added to epic.

**Comment by kltm** [comment]
Splitting into about and footer.
